#!/bin/bash

cd ~

echo "Fixing dotfiles..."

rm -rf .bash_aliases
ln -s ~/Dropbox/OSX\ -\ Terminal/.bash_aliases .bash_aliases

rm -rf .bash_profile
ln -s ~/Dropbox/OSX\ -\ Terminal/.bash_profile .bash_profile

rm -rf .bash_prompt
ln -s ~/Dropbox/OSX\ -\ Terminal/.bash_prompt .bash_prompt

rm -rf .gitconfig
ln -s ~/Dropbox/OSX\ -\ Terminal/.gitconfig .gitconfig

rm -rf .wgetrc
ln -s ~/Dropbox/OSX\ -\ Terminal/.wgetrc .wgetrc

rm -rf .curlrc
ln -s ~/Dropbox/OSX\ -\ Terminal/.curlrc .curlrc

echo "Adding missing commands..."

rm -rf /usr/local/bin/subl
ln -s "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl


echo "Pointed local configuration to Dropbox..."