#!/bin/bash

cd ~

echo "Fixing dotfiles..."

rm -rf .bash_aliases
ln -s ~/Projects/dotfiles/.bash_aliases .bash_aliases

rm -rf .bash_profile
ln -s ~/Projects/dotfiles/.bash_profile .bash_profile

rm -rf .bash_prompt
ln -s ~/Projects/dotfiles/.bash_prompt .bash_prompt

rm -rf .gitconfig
ln -s ~/Projects/dotfiles/.gitconfig .gitconfig

rm -rf .wgetrc
ln -s ~/Projects/dotfiles/.wgetrc .wgetrc

rm -rf .curlrc
ln -s ~/Projects/dotfiles/.curlrc .curlrc

echo "Adding missing commands..."

rm -rf /usr/local/bin/subl
ln -s "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl

echo "Pointed local configuration to dotfiles..."